---
trigger:
- main 
- dev 
- ad 
pool: devops
stages:
- stage: build
  jobs:
  - job: buildpackage
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/target/surefire-reports/TEST-*.xml'    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'target/*.jar' 
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/*.jar' 
        replaceExistingArchive: false

