---
trigger:
- dev

pool: 
- Devops

stages:
- stage: build
  jobs:
  - job: build package
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        javaHomeOption: 'JDKVersion'
        jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'

- stage: Archive artifacts
  jobs:
  - job: Archive artifacts
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)' 
        includeRootFolder: true 
        archiveType: 'zip' 
        tarCompression: 'none' 
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
        replaceExistingArchive: true 

- stage: publish Junit test testResults
  jobs:
  - job: publish Junit test testResults
    steps:
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
