---
pool: k8s

trigger: 
  - ppm 

stages:
  - stage: build 
    jobs: 
      - job: dockerimagebuild
        steps: 
          - task: Docker@2 
            inputs: 
              containerRegistry: acr_id 
              repository: spc 
              command: 'buildAndPush' 
              Dockerfile: Dockerfile 
              tags: '$(Build.BuildId)' 
  - stage: deploy 
    dependsOn: build
    condition: succeeded()
    jobs: 
      - job: deployimage 
        steps: 
          - task: Kubernetes@1 
            inputs: 
              connectionType: Azure Resource Manager 
              azureSubscriptionEndpoint: acrm_id 
              azureResourceGroup: myResourceGroup
              kubernetesCluster: myAKSCluster 
              command: apply 
              useConfigurationFile: true 
              configurationType: configuration 
              configuration: deployments/spcapp.yaml    