--- 
- name: install java 
  hosts: all 
  become: true
  tasks: 
    - name: install java and update cache 
      ansible.builtin.apt: 
        name: openjdk-11-jdk 
        state: present 
        update_cache: yes 